# Generated by Django 4.1.6 on 2023-03-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('worspacename', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('colorscheme', models.IntegerField()),
                ('participating', models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('creation_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.IntegerField()),
                ('sprint', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('assignee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(max_length=20)),
                ('authentication_status', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(default='image/jpg', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
